version: 2.1
jobs:
  release-production:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run: |
          git clone --recursive https://github.com/typedb-osi/website.git
          cd website
          git config user.name $REPO_GITHUB_USERNAME
          git config user.email $REPO_GITHUB_EMAIL
          pushd src/docs
          git checkout $CIRCLE_SHA1
          popd
          git add src/docs
          git commit -m "//ci:release-docs: typedb-osi/docs@$CIRCLE_SHA1"
          git push "https://$REPO_GITHUB_TOKEN@github.com/typedb-osi/website.git"
workflows:
  docs:
    jobs:
      - release-production:
          filters:
            branches:
              only: master
